# Generated by Django 4.0.5 on 2022-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shippingaddress_apt_no_shippingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='apt_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
