# Generated by Django 4.0.5 on 2022-06-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_shippingaddress_apt_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='postalcode',
        ),
    ]
