# Generated by Django 4.0.5 on 2022-06-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_shippingaddress_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taxPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
